[package]
version = "0.1.0"
name = "hello-world-script"
edition = "2021"
# Other package configurations
build = "build.rs"

[dependencies]
sp1-core = { git = "https://github.com/succinctlabs/sp1.git" }

